config/routes.rb
Hackboard::Application.routes.draw do

  devise_for :users

  resources :posts do
    collection do
      get :mine, as: :my
    end

    resources :comments
  end

  match "user/posts" => "posts#mine"

  resources :users do
    resources :posts
  end

  root to: 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id

  belongs_to :post
  belongs_to :user

  validates :user, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :link, :image

  has_many :comments
  belongs_to :user

  has_attached_file :image,
  	styles: {
  		thumb: '100x100>',
  		small: '150x150>',
  		medium: '200x200>'
  	},
    storage: :s3,
    s3_credentials: {
      access_key_id: 'AKIAJNUSQQMYYELN5VZQ',
      secret_access_key: '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',
      bucket: 'hackeryou'
    }

  validates :description, presence: true
  validates :link, presence: true,
  				   format: /^http:\/\/.+?/
  validates :user, presence: true
  				   #http://facebook.com

  validates_attachment_presence :image

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
  has_many :comments

  def email_required?
  	uid.blank? 
  end

  def password_required?
  	uid.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :authenticate_user!

	def create
		post = Post.find(params[:post_id])
		@comment = post.comments.build(params[:comment])
		@comment.user = current_user

		user = post.user

		if @comment.save
			MyMailer.comment_email(user,@comment).deliver
			redirect_to posts_path
		else
			render 'new'
		end
	
		

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate_user!

	

	def index
		#render text: params.to_s
		user_id = params[:user_id]
		if user_id
			@posts = Post.includes(:comments).where(user_id: user_id)
		else
			@posts = Post.includes(:comments)
		end
		# if params[:description]
		# 	@posts = @posts.where("description LIKE ?", 
		# 		"%#{params[:description]}%")
		# end
		@q = @posts.search(params[:q])
		@posts = @q.result

	end

	def new
		@post = Post.new
	end

	def create

		@post = current_user.posts.build(params[:post])

		# @post = Post.new(params[:post])
		if @post.valid?
			@post.save
			redirect_to posts_path
		else
			render :new
		end
	end

	def mine
		@posts = current_user.posts
		render :index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

def byline(object)
		if object.user == current_user
			"Posted by You"
		else
			"Posted by #{object.user.email}"
		end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper

	def comment_byline(comment)
		if comment.user == current_user
			"Posted by You"
		else
			"Posted by #{comment.user.email}"
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper

	def comment_byline(post)
		if post.user == post_user
			"Posted by You"
		else
			"Posted by #{post.user.email}"
		end
	end

end

app/views/comments/_comment.html.erb
<li><%= comment.body %></li>
User: <%= comment.user.email %>

app/views/comments/_form.html.erb
<%= form_for [comment.post, comment] do |f| %>

	<%= f.text_field :body, placeholder: 'Add a comment...' %>
	<%= f.submit %>

<% end %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Hackboard</a>
    <% if user_signed_in? %>
	    <ul class="nav">
	      <li class="active">
	      	<%= link_to "Add Posts", new_post_path %></li>
	      <li class="active">
	      	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	    </ul>
	<% else %>
		<%= link_to "Sign In", new_user_session_path %>
	<% end %>

  </div>
</div>

<div class='container'>

	<%= yield %>
	
</div>

</body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>

<%#= form_tag posts_path, method: :get do %>
	<%#= label_tag :description, "Search" %>
	<%#= text_field_tag :description, params[:description] %>
	<%#= submit_tag "Search" %>
<%# end %>

<%= search_form_for @q do |f| %>
	<%= f.label :description_cont, "Search Description" %>
	<%= f.text_field :description_cont %>
	
	<%= f.label :link_cont, "Search Link" %>
	<%= f.text_field :link_cont %>
	<%= f.submit "Submit" %>
<% end %>

<div class = 'row'>
<% @posts.each_with_index do |p, i| %>

	<% if i % 4 == 0 %>
		</div><div class='row'>
	<% end %>

	<div class= 'span3'>
			<div><%= link_to p.description, post_path(p) %></div>
			<div>User: <%= p.user.email %> </div>

			<%= link_to "Go!", p.link %>
			<%#= link_to "Show", post_path(p) %>

			<%= image_tag p.image.url(:thumb) %>

			<div><%= byline(p) %> </div>


		<ul>
		<%= render p.comments%>
		<li><%= render 'comments/form',
						comment: p.comments.build,
						post: p %></li>
		</ul>
	</div>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>


<% if @post.errors.any? %>
	<div class='alert alert-error' >	
		<strong> Error: </strong> Your post was invalid!
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>	


<%= form_for @post, html: {multipart: true} do |f| %>

	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div>
		<%= f.label :link %>
		<%= f.text_field :link %>
	</div>

	<div>
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>

	<%= f.submit "Save Post", class: 'btn btn-primary' %>

<% end %>

app/views/posts/show.html.erb
<h1>Post</h1>